In [1]:
import pandas as pd

In [2]:
data =pd.read_csv("italy_earthquakes_from_2016-08-24_to_2016-11-30.csv")

In [3]:
data

                         Time  Latitude  Longitude  Depth/Km  Magnitude
0     2016-08-24 03:36:32.000   42.6983    13.2335       8.1        6.0
1     2016-08-24 03:37:26.580   42.7123    13.2533       9.0        4.5
2     2016-08-24 03:40:46.590   42.7647    13.1723       9.7        3.8
3     2016-08-24 03:41:38.900   42.7803    13.1683       9.7        3.9
4     2016-08-24 03:42:07.170   42.7798    13.1575       9.7        3.6
...                       ...       ...        ...       ...        ...
8081  2016-11-30 18:39:27.600   42.8903    13.0197      10.7        2.0
8082  2016-11-30 18:43:14.850   42.9443    13.2003       8.6        2.6
8083  2016-11-30 20:18:27.550   43.0092    13.1288       8.0        2.2
8084  2016-11-30 20:45:11.780   43.0197    13.1017       9.3        2.7
8085  2016-11-30 20:54:35.890   42.9935    13.0753       9.5        2.3

[8086 rows x 5 columns]

In [5]:
import pandas as pd
import plotly.graph_objects as go

data.head()

fig = go.Figure(data = go.Scattergeo(
    lon = data["Longitude"],
    lat = data["Latitude"],
    text = data["Time"],
    mode = "markers",
    marker = dict(
        size = 12,
        opacity = 0.8,
        reversescale = True,
        autocolorscale = True,
        symbol = 'circle',
        line = dict(
            width = 1,
            color = 'rgba(102, 102, 102)'
        ),
        cmin = 0,
        color = data['Magnitude'],
        cmax = data['Magnitude'].max(),
        colorbar_title = "Magnitude"
    )
))

fig.update_layout(
    title = "Earthquakes in Turkey",
    geo = dict(
        scope = "world",
        showland = True,
    )
)

fig.write_html('first_figure.html', auto_open=True)